"""
04_react_agent_with_tools.py
=============================
Topic: The ReAct (Reasoning + Acting) Agent Pattern in LangGraph

Key Concepts for 2026:
1. ReAct Loop: An LLM dynamically reasons, invokes tools, and inspects tool results.
2. MessagesState: Built-in LangGraph state using message reducers (`add_messages`).
3. ToolNode: Built-in node that executes tool calls generated by the model.
4. tools_condition: Conditional edge function checking if the model requested a tool.
"""

from typing import Annotated
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END, MessagesState
from langgraph.prebuilt import ToolNode, tools_condition
from utils import get_chat_model, print_section


# -------------------------------------------------------------
# 1. Defining Agent Tools with @tool
# -------------------------------------------------------------
@tool
def calculator(expression: str) -> str:
    """Calculates mathematical expressions. Example: '25 * 4'"""
    print(f"   [TOOL EXECUTION] Calculator running: '{expression}'")
    try:
        # Safe evaluation for demo arithmetic
        allowed = set("0123456789+-*/() .")
        if all(c in allowed for c in expression):
            return str(eval(expression))
        return "Unsupported expression characters."
    except Exception as e:
        return f"Calculation error: {e}"


@tool
def get_weather(city: str) -> str:
    """Fetches real-time weather information for a specified city."""
    print(f"   [TOOL EXECUTION] Weather service querying: '{city}'")
    city_lower = city.lower()
    if "san francisco" in city_lower:
        return "San Francisco: 64°F, Partially Cloudy, Foggy evening expected."
    elif "new york" in city_lower:
        return "New York: 72°F, Sunny and pleasant."
    return f"{city}: 70°F, Clear skies."


tools = [calculator, get_weather]


# -------------------------------------------------------------
# 2. Agent Node Definition
# -------------------------------------------------------------
def agent_node(state: MessagesState) -> dict:
    """The reasoning engine: LLM with bound tools."""
    print("\n-> [Agent Node] Analyzing message history and deciding action...")
    model = get_chat_model()
    model_with_tools = model.bind_tools(tools)
    response = model_with_tools.invoke(state["messages"])
    return {"messages": [response]}


def main():
    print_section("04: ReAct Agent with Tools in LangGraph")

    # ---------------------------------------------------------
    # 3. Construct the ReAct Graph
    # ---------------------------------------------------------
    builder = StateGraph(MessagesState)

    # Add agent node and prebuilt ToolNode
    builder.add_node("agent", agent_node)
    builder.add_node("tools", ToolNode(tools))

    # Flow:
    # START -> agent
    # agent -> (tools_condition) -> tools OR END
    # tools -> agent (cycle back to allow LLM to interpret tool result!)
    builder.add_edge(START, "agent")
    builder.add_conditional_edges(
        "agent",
        tools_condition,  # Checks if last message contains `tool_calls`
        {"tools": "tools", END: END}
    )
    builder.add_edge("tools", "agent")

    agent_app = builder.compile()

    # ---------------------------------------------------------
    # 4. Run the Agent with a Multi-Step Tool Query
    # ---------------------------------------------------------
    query = "What is the weather in San Francisco and please calculate 25 * 4?"
    print(f"\nUser Query: '{query}'")

    input_messages = [
        SystemMessage(content="You are a helpful ReAct agent equipped with calculator and weather tools."),
        HumanMessage(content=query)
    ]

    # Stream graph execution to observe the ReAct loop in real-time
    final_output = agent_app.invoke({"messages": input_messages})

    print("\n--- Conversation History (ReAct Trace) ---")
    for msg in final_output["messages"]:
        sender = type(msg).__name__
        if hasattr(msg, "tool_calls") and msg.tool_calls:
            print(f"[{sender}] Tool Call Request: {msg.tool_calls}")
        elif sender == "ToolMessage":
            print(f"[{sender}] Tool Response: {msg.content}")
        else:
            print(f"[{sender}]: {msg.content}")

    print("\n[SUCCESS] Lesson 04 completed. You observed a full ReAct loop in LangGraph!")


if __name__ == "__main__":
    main()
